### ISSUE TITLE
CP_Font_Free is no longer in the API but it is still in the wiki

### ISSUE THREAD

**Issue by gwong-dp** [DigiPen-Faculty/CProcessing#16]
CP_Font_Free is no longer in the API (cprocessing.h) but it is still in the wiki as a broken link. 
CP_Font_Load's example still references CP_Font_Free.

Without CP_Font_Free, users noticed an inconsistency between CP_Font's and CP_Image's API. CP_Image has a Load/Free pair while CP_Font does not, which causes users to be confused about CProcessing's philosophy behind resource management. Users who are monitoring their RAM usage also prefer to have a way to free their fonts (for example, using one set of fonts for state A and using another set of fonts for state B).

I suggest that we reintroduce CP_Font_Free to allow users to have full control over their application's memory management. When time permits, we will implement this and test in the Singapore branch first.

**Comment by justinchambers-dp** [comment]
#28 This was a quite a bit more complex than I initially assumed.  I suspect the complexity is what caused us to leave out the function back in the beginning for some reason.

This PR adds the CP_Font_Free function to CProcessing so now all asset types have matching Load/Free pairs and proper memory management of fonts can be handled by the user.
