### ISSUE TITLE
CP_Input_GetMouseWorldY() Does not calculate CP_Settings_Scale() & CP_Settings_ApplyMatrix() properly

### ISSUE THREAD

**Issue by CamilaBasualdo** [DigiPen-Faculty/CProcessing#18]
When using canvas transforms such as CP_Settings_Scale() & CP_Settings_ApplyMatrix(), CP_Input_GetMouseWorldY() gives a value thats (1/scale^3) instead of (1/scale)
Main.c: [main.c.txt](https://github.com/DigiPen-Faculty/CProcessing/files/9885230/main.c.txt)
![Proof 1](https://user-images.githubusercontent.com/73839783/198501430-f95e0f26-531a-43d5-890d-f6a15cf11d8f.jpeg)
![Proof 2](https://user-images.githubusercontent.com/73839783/198501433-d69d7f6a-ae19-4134-8184-fa3731e2cd25.jpeg)
<img width="539" alt="Proof 3" src="https://user-images.githubusercontent.com/73839783/198501434-29b9ae62-f483-4440-afb3-7122325e1144.png">

**Comment by justinchambers-dp** [comment]
The matrix inverse function needs separate input and output values.  Out code for screenToWorld was just passing the same matrix into the in and out values and was getting mangled in the process.

**Comment by justinchambers-dp** [comment]
Thank you for the great sample code and clear explanation of the issue!
Solved in #25
