### ISSUE TITLE
More options for CP_POSITION_MODE

### ISSUE THREAD

**Issue by gwong-dp** [DigiPen-Faculty/CProcessing#19]
Students requested for more options for CP_POSITION_MODE, or some kind of option to determine where to draw. 
Right now it's limited to center and top left.

**Comment by justinchambers-dp** [comment]
I believe this is Won't Fix.  We aren't providing a complete UI anchoring system or arbitrary pivot point management.  All of those capabilities are still possible by offsetting draw position and/or using matrix transforms.
