### ISSUE TITLE
CP_Image_Load does not reuse slots that it freed. 

### ISSUE THREAD

**Issue by gwong-dp** [DigiPen-Faculty/CProcessing#20]
As per title, CP_Image_Load does not reuse freed CP_Image slots in its pool.

**Comment by GeraldWongDP** [comment]
Noticed that #14 has a lot of code that might affect the implementation of this. 
It is a pull request from almost 1 year ago at this point of writing.

**Comment by justinchambers-dp** [comment]
Yes, I think #23 has all the necessary image fixes especially better memory pool organization and use.
