### ISSUE TITLE
Requesting a CP_Vector function that returns anti-clockwise/clockwise angle between two vectors

### ISSUE THREAD

**Issue by gwong-dp** [DigiPen-Faculty/CProcessing#21]
Student requested a CP_Vector function that returns anti-clockwise/clockwise angle between two vectors. We might want to be careful about the coordinate system of CProcessing because since y-axis is downwards, usual clockwise/anti-clockwise formulas might end up being flipped.

Might also want to consider a CP_Vector_Sign that will return -1 when a vector is on the left side of another vector, 1 when it is on the right side.

**Comment by GeraldWongDP** [comment]
Implemented in Singapore branch here: 6667d889cac5490c49b61379d02bb4b911a4a414

Will update the wiki once we merge.

**Comment by justinchambers-dp** [comment]
Pull request #32 adds CP_Vector_AngleCW and CCW.  CW returns positive [0, 360) and CCW returns negative [0, -360).  This way you can dump the same angle values in any of the rotation or advanced drawing functions and get consistent results.

Thanks for leading the way on this one Singapore!
