### ISSUE TITLE
Make the DrawPoint function use the Stroke setting instead of the Fill setting

### ISSUE THREAD

**Issue by ianelsbree** [DigiPen-Faculty/CProcessing#4]
The CP_Graphics_DrawPoint() function currently uses the setting CP_Settings_Fill to draw the point's color. It makes more sense to use the CP_Settings_Stroke color to draw points, as lines are drawn with the stroke color and a line is just a set of points. A point is essentially one point of a stroke and does not have a body to fill with a fill color. Additionally, the [Processing ](https://processing.org/reference/point_.html) and [p5.js](https://p5js.org/reference/#/p5/point) libraries both use the stroke() setting to draw point colors, so using CP_Settings_Stroke for points in CProcessing would make it more consistent with the similar libraries.

**Comment by beppyboo** [comment]
This change would also reduce the number of times that the stroke and fill settings would need to be changed when drawing points and lines in the same color, reducing the chance of bugs related to incorrect color settings.

**Comment by AEllinger** [comment]
Thanks for the suggestion, we’ll have a conversation about it. Personally I do agree that using stroke would make more sense.

**Comment by justinchambers-dp** [comment]
Would it still be a single pixel OR if we switch to thinking about it in the context of stroke, does it also take into account the stroke weight?

**Comment by justinchambers-dp** [comment]
#24
