### ISSUE TITLE
Other options for drawing rectangles

### ISSUE THREAD

**Issue by AEllinger** [DigiPen-Faculty/CProcessing#6]
Should we add an option to draw rectangles using two points?

**Comment by beppyboo** [comment]
I think this would be a fine addition that may cut down on calculations in some circumstances.

**Comment by justinchambers-dp** [comment]
I vote no.  It's easy enough to compute the width/height from points if that is how the user is tracking position or size.  And not adding another function helps keep the API clean and consistent since there wouldn't be anything matching for other primitives.
