### ISSUE TITLE
can we have a CP_Image_DrawSubImageAdvanced?

### ISSUE THREAD

**Issue by CoriullusFox** [DigiPen-Faculty/CProcessing#7]
we have CP_Image_DrawAdvanced that allows drawing rotated images, and we have CP_Image_DrawSubImage that allows providing uv coordinates for the image so we can draw a portion of the image.
but we don't have a function that allows both.

**Comment by momohoudai** [comment]
This is fixed in the Singapore branch: ccaca3d1d2cc6eb0f1407df3b109c035c4d0976e

**Comment by GeraldWongDP** [comment]
This is fixed in the Singapore branch: ccaca3d1d2cc6eb0f1407df3b109c035c4d0976e
